INSERT INTO
	POST (id, status, title, content, tags)
VALUES
  	(1, 'draft', 'The best Javascript frameworks in 2020', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vulputate tortor ut diam rhoncus cursus. Duis blandit sed justo ac tristique. Maecenas suscipit felis non sem sollicitudin, vitae dignissim tellus pulvinar. Aliquam in ex vitae sem volutpat feugiat. Aenean sollicitudin facilisis nibh. In et nisi lobortis, tincidunt justo sit amet, luctus mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer blandit congue augue, nec dignissim est accumsan a. Suspendisse ac massa vehicula, convallis eros venenatis, fermentum dui. Ut elementum erat vitae magna pulvinar finibus. Pellentesque tristique libero eu tempor varius. Nulla facilisi. Morbi consequat metus id felis condimentum euismod. Sed sed risus at ex dictum rhoncus. Maecenas ipsum nunc, auctor sit amet dolor non, vehicula placerat nibh.', 'Javascript'),
	(2, 'published', 'Vim in 5 minutes', 'Vivamus vel leo lectus. Phasellus facilisis neque congue eros ultrices viverra. Quisque facilisis nisi elit, non feugiat sem pharetra non. Nulla facilisi. Vestibulum at hendrerit augue, a placerat risus. Pellentesque posuere, risus et ornare facilisis, orci massa vestibulum felis, nec molestie dolor augue sed nulla. Integer eu risus sed nunc commodo tincidunt ac lacinia magna. Pellentesque tempus, nulla vitae cursus commodo, est nisl convallis sem, hendrerit ultricies sapien leo nec quam.', 'Bash,Vim'),
  	(3, 'published', 'Prototyping with JShell', 'Donec nisi libero, porta a erat eget, facilisis molestie nibh. Nulla sodales pulvinar vestibulum. Aenean velit est, posuere eu pulvinar ac, lacinia sit amet nisl. Curabitur sed est convallis, lacinia dui non, bibendum lacus. Vivamus condimentum, risus quis congue feugiat, eros tellus mattis tellus, sit amet aliquam erat quam ultrices ligula. Duis libero nisl, pharetra quis nulla ac, tempor blandit est. Suspendisse fringilla nulla non nunc faucibus venenatis. Sed ut mauris vel felis molestie viverra. Maecenas tortor diam, sagittis et elit eu, vulputate viverra lacus. Morbi pellentesque ante nec nulla condimentum ornare. Duis dui elit, hendrerit quis mauris vel, iaculis vulputate ipsum.', 'Java'),
	(4, 'draft', 'Terraform best practices', 'Suspendisse scelerisque sem ut ligula volutpat cursus. Praesent aliquet, arcu in ornare ornare, nisl augue laoreet ex, quis mattis lorem odio in nulla. Etiam nec nunc erat. Praesent tristique rutrum lacus sed condimentum. Nunc sagittis est mi, vel consequat orci dapibus sed. Donec luctus, elit vitae eleifend sagittis.', 'Terraform,AWS'),
  	(5, 'draft', 'Scripting with Terraform', 'Aliquam erat volutpat. Maecenas dolor tortor, mattis at fermentum at, rutrum sollicitudin urna. Integer mi ante, maximus tristique sollicitudin pharetra, gravida vel felis. Vestibulum eu nunc sem. Duis egestas sollicitudin dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus.', 'Terraform'),
  	(6, 'published', 'Git: merge or rebase?', 'Donec nisi libero, porta a erat eget, facilisis molestie nibh. Nulla sodales pulvinar vestibulum. Aenean velit est, posuere eu pulvinar ac, lacinia sit amet nisl. Curabitur sed est convallis, lacinia dui non, bibendum lacus. Vivamus condimentum, risus quis congue feugiat, eros tellus mattis tellus, sit amet aliquam erat quam ultrices ligula.', 'Git'),
  	(7, 'published', 'Error handling in Bash', 'Integer cursus libero vel massa placerat, a efficitur nunc vulputate. Nam elementum, felis nec vehicula viverra, odio sem venenatis ex, sit amet laoreet eros diam quis lacus. Ut tincidunt ante ut elit consectetur, vel suscipit quam elementum. Donec quis nunc neque. Proin sed ornare elit, vel vestibulum lectus. Curabitur sit amet facilisis est, a gravida metus. Nunc suscipit purus at dapibus vehicula. Donec nisl eros, rutrum vitae dui nec, dictum finibus nunc. Nulla consectetur eros est, volutpat rhoncus massa tristique vehicula. Mauris nec porttitor enim, ut rutrum lectus. Pellentesque sed lobortis tellus. In hac habitasse platea dictumst. Sed ac turpis sit amet tellus dapibus feugiat. Phasellus eu mi sapien. Aliquam id tellus suscipit diam posuere tempor. Proin suscipit, risus quis cursus semper, nisi lorem finibus mi, malesuada volutpat lorem dui in ligula.', 'Bash'),
  	(8, 'published', 'Intro to the CORS headers', 'Vestibulum molestie, felis quis egestas lacinia, mi enim mattis quam, in consequat purus libero ut ipsum. In id condimentum est. Aliquam erat volutpat. Maecenas dolor tortor, mattis at fermentum at, rutrum sollicitudin urna. Integer mi ante, maximus tristique sollicitudin pharetra, gravida vel felis. Vestibulum eu nunc sem. Duis egestas sollicitudin dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus.', 'CORS,Security'),
  	(9, 'draft', 'Security enhancements in Java 13', 'Vivamus vel leo lectus. Phasellus facilisis neque congue eros ultrices viverra. Quisque facilisis nisi elit, non feugiat sem pharetra non. Nulla facilisi. Vestibulum at hendrerit augue, a placerat risus. Pellentesque posuere, risus et ornare facilisis, orci massa vestibulum felis, nec molestie dolor augue sed nulla. Integer eu risus sed nunc commodo tincidunt ac lacinia magna. Pellentesque tempus, nulla vitae cursus commodo', 'Java,Security'),
  	(10, 'published', 'Bash vs ZSH', 'Convallis sem, hendrerit ultricies sapien leo nec quam. Vestibulum molestie, felis quis egestas lacinia, mi enim mattis quam, in consequat purus libero ut ipsum. In id condimentum est. Aliquam erat volutpat. Maecenas dolor tortor, mattis at fermentum at, rutrum sollicitudin urna. Integer mi ante, maximus.', 'ZSH,Bash'),
  	(11, 'published', 'Java modules', 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer blandit congue augue, nec dignissim est accumsan a. Suspendisse ac massa vehicula, convallis eros venenatis, fermentum dui. Ut elementum erat vitae magna pulvinar finibus. Pellentesque tristique libero eu tempor varius. Nulla facilisi. Morbi consequat metus id felis condimentum euismod. Sed sed risus at ex dictum rhoncus', 'Java'),
  	(12, 'published', 'The wonderful PlantUML', 'Nulla consectetur eros est, volutpat rhoncus massa tristique vehicula. Mauris nec porttitor enim, ut rutrum lectus. Pellentesque sed lobortis tellus. In hac habitasse platea dictumst. Sed ac turpis sit amet tellus dapibus feugiat. Phasellus eu mi sapien. Aliquam id tellus suscipit diam posuere tempor. Proin suscipit, risus quis cursus semper, nisi lorem finibus mi, malesuada volutpat lorem dui in ligula.', 'PlantUML,Javascript,Ruby');
