DROP TABLE IF EXISTS POST;
CREATE TABLE POST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  status VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  content VARCHAR(5000) NOT NULL,
  tags VARCHAR(250) NOT NULL
);
